const data = {
  games: [
    {
      id: "2331",
      name: "SkatingMaster",
      url: "https://uptapapi.uptap.com/h5Game/?type=Game&platform=uptapin&appid=SkatingMaster",
      icon: "https://cdn.iwantalipstick.com/gameicon2/jpg/SkatingMaster.jpg",
      category: "Racing",
      description:
        "This is an ice skating game.You need to beat your opponent to win the game. Along the way you can collect props to help you win the game, but there will also be obstacles that slow you down.",
      isPortrait: "True",
      time: "2022/6/16 15:01:00",
      title: "Skating Master",
      slug: "skating-master",
      stars: "4.3",
      played: "197.5k",
    },
    {
      id: "2329",
      name: "LittleFarm",
      url: "https://uptapapi.uptap.com/h5Game/?type=Game&platform=uptapin&appid=LittleFarm",
      icon: "https://cdn.iwantalipstick.com/gameicon2/jpg/LittleFarm.jpg",
      category: "Simulation",
      description:
        "You need to run your farm well.Raising sheep, feeding pigs, planting, producing. . . You need to do a lot to manage your farm well.",
      isPortrait: "True",
      time: "2022/6/16 15:01:00",
      title: "Little Farm",
      slug: "little-farm",
      stars: "4.2",
      played: "163.4k",
    },
    {
      id: "2327",
      name: "BigEater",
      url: "https://uptapapi.uptap.com/h5Game/?type=Game&platform=uptapin&appid=BigEater",
      icon: "https://cdn.iwantalipstick.com/gameicon2/jpg/BigEater.jpg",
      category: "Casual",
      description:
        "All you need to do is to fill the belly of the big eater.Tap the screen to control the timing of the bamboo stick jumping and landing. Collect more food and send it to the mouth of the big eater. Remember, consecutive clicks can jump higher.",
      isPortrait: "True",
      time: "2022/6/16 15:01:00",
      title: "Big Eater",
      slug: "big-eater",
      stars: "4.3",
      played: "136.8k",
    },
    {
      id: "2319",
      name: "ShootingStar",
      url: "https://uptapapi.uptap.com/h5Game/?type=Game&platform=uptapin&appid=ShootingStar",
      icon: "https://cdn.iwantalipstick.com/gameicon2/jpg/ShootingStar.jpg",
      category: "Action",
      description:
        "Throw the basketball into the hoop.You need to control the strength and angle of your fingers to throw as many basketballs as possible into the hoop. When you reach the target score, you can pass the level.",
      isPortrait: "True",
      time: "2022/4/8 14:03:00",
      title: "Shooting Star",
      slug: "shooting-star",
      stars: "4.1",
      played: "186.0k",
    },
    {
      id: "2320",
      name: "ColorHammer",
      url: "https://uptapapi.uptap.com/h5Game/?type=Game&platform=uptapin&appid=ColorHammer",
      icon: "https://cdn.iwantalipstick.com/gameicon2/jpg/ColorHammer.jpg",
      category: "Action",
      description:
        "Hit more nails to pass the level.You need to control the direction of the hammer to hit the nails. The hammer can only hit nails of the same color, and if it hits other colors, the level may fail.",
      isPortrait: "True",
      time: "2022/4/8 14:03:00",
      title: "Color Hammer",
      slug: "color-hammer",
      stars: "4.5",
      played: "187.2k",
    },
    {
      id: "2306",
      name: "RoofRunner",
      url: "https://uptapapi.uptap.com/h5Game/?type=Game&platform=uptapin&appid=RoofRunner",
      icon: "https://cdn.iwantalipstick.com/gameicon2/jpg/RoofRunner.jpg",
      category: "Casual",
      description:
        "Remain focused, remain swift! Slide left and right to move the runner, the obstacles on your way wont stop you but cost you some more time to pass, compared with dodging them. You can also try various skins which will bring you more fun in the roof runs.",
      isPortrait: "True",
      time: "2022/3/25 11:28:00",
      title: "Roof Runner",
      slug: "roof-runner",
      stars: "4.3",
      played: "169.9k",
    },
    {
      id: "2301",
      name: "CleverRescue",
      url: "https://uptapapi.uptap.com/h5Game/?type=Game&platform=uptapin&appid=CleverRescue",
      icon: "https://cdn.iwantalipstick.com/gameicon2/jpg/CleverRescue.jpg",
      category: "Puzzle",
      description:
        "See? They are already there! Drag the rope and stick it to the pole, make sure the path is accessible, then press and hold the screen to transport the crowd from SOS spot to safety.",
      isPortrait: "True",
      time: "2022/3/14 11:35:00",
      title: "Clever Rescue",
      slug: "clever-rescue",
      stars: "4.4",
      played: "193.1k",
    },
    {
      id: "2298",
      name: "EasyCharger",
      url: "https://uptapapi.uptap.com/h5Game/?type=Game&platform=uptapin&appid=EasyCharger",
      icon: "https://cdn.iwantalipstick.com/gameicon2/jpg/EasyCharger.jpg",
      category: "Puzzle",
      description:
        "Tap the screen and use your brain, try to plug all the chargers in the boards. Sometimes you have to manage the right sockets for chargers to plug in according to their various sizes, and some other times you have to turn on some electric devices first to help you successfully plug in all chargers.",
      isPortrait: "True",
      time: "2022/2/18 14:39:00",
      title: "Easy Charger",
      slug: "easy-charger",
      stars: "4.2",
      played: "160.6k",
    },
    {
      id: "2296",
      name: "BlockMaster",
      url: "https://uptapapi.uptap.com/h5Game/?type=Game&platform=uptapin&appid=BlockMaster",
      icon: "https://cdn.iwantalipstick.com/gameicon2/jpg/BlockMaster.jpg",
      category: "Puzzle",
      description:
        "Drag the blocks left and right, make them fall and fill the space. Blocks will be cleared when they form a full line. Your every move will randomly raise some blocks from the bottom, try to clear more blocks before they reach to the top as you can.",
      isPortrait: "True",
      time: "2022/2/18 14:39:00",
      title: "Block Master",
      slug: "block-master",
      stars: "4.2",
      played: "172.7k",
    },
    {
      id: "2295",
      name: "FruitsFall",
      url: "https://uptapapi.uptap.com/h5Game/?type=Game&platform=uptapin&appid=FruitsFall",
      icon: "https://cdn.iwantalipstick.com/gameicon2/jpg/FruitsFall.jpg",
      category: "Casual",
      description:
        "Join this juicy fruits festival now! Slide the laser to the position you want to drop the fruit in this transparent box,  the dropped fruits will freely fall and roll in the box. When two same fruits contact, they will merge into one bigger fruit, the more fruits you merge, the higher points you will get.",
      isPortrait: "True",
      time: "2021/12/30 15:37:00",
      title: "Fruits Fall",
      slug: "fruits-fall",
      stars: "4.3",
      played: "162.0k",
    },
    {
      id: "2276",
      name: "FierceCity",
      url: "https://uptapapi.uptap.com/h5Game/?type=Game&platform=uptapin&appid=FierceCity",
      icon: "https://cdn.iwantalipstick.com/gameicon2/jpg/FierceCity.jpg",
      category: "Action",
      description:
        "I always shoot first, guns blazing! Slide left and right to move, you will keep shooting at the enemies approaching you. Tap the button on the right to roll and escape from enemies' attack if need. Be careful of your mag because you are unable to attack during the seconds you reload. When facing a powerful boss, you can call robots and airforce for help.",
      isPortrait: "True",
      time: "2021/11/29 18:51:00",
      title: "Fierce City",
      slug: "fierce-city",
      stars: "4.1",
      played: "154.2k",
    },
    {
      id: "2272",
      name: "BrainMaster",
      url: "https://uptapapi.uptap.com/h5Game/?type=Game&platform=uptapin&appid=BrainMaster",
      icon: "https://cdn.iwantalipstick.com/gameicon2/jpg/BrainMaster.jpg",
      category: "Puzzle",
      description:
        "I bet you never got a brain training like this!Here you will get a series of test, which include many different questions.You have to get your brain in gear and come up with answers. You should be aware that sometime the questions are not asked as their literal meaning express, only smart guys can figure it out! ",
      isPortrait: "True",
      time: "2021/11/5 13:58:00",
      title: "Brain Master",
      slug: "brain-master",
      stars: "4.4",
      played: "142.3k",
    },
    {
      id: "276",
      name: "JumpSmash",
      url: "https://uptapapi.uptap.com/h5Game/?type=Game&platform=uptapin&appid=JumpSmash",
      icon: "https://cdn.iwantalipstick.com/gameicon2/jpg/JumpSmash.jpg",
      category: "Casual",
      description:
        "Control the jumping ball to the bottom. Press the screen to smash the bricks, release to stop smashing and stay jumping. Only the color bricks can be smashed, and the black brick will break you if you try to smash it. Straight smashing will charge your super which can destroy any bricks for seconds.",
      isPortrait: "True",
      time: "2021/6/18 16:35:00",
      title: "Jump Smash",
      slug: "jump-smash",
      stars: "4.2",
      played: "122.4k",
    },
    {
      id: "272",
      name: "MrRacer",
      url: "https://uptapapi.uptap.com/h5Game/?type=Game&platform=uptapin&appid=MrRacer",
      icon: "https://cdn.iwantalipstick.com/gameicon2/jpg/MrRacer.jpg",
      category: "Action",
      description:
        "Fired up and ready to serve. Pass and crash, I am in the rush! Drive your car as long-distance as possible till your fuel run out. Press the screen to keep speeding up, you can also get extra speed-up by crashing other cars. You got different goals in different modes, try to win a higher rank in challenge mode. Use coins to upgrade your racers.",
      isPortrait: "True",
      time: "2021/5/21 18:48:00",
      title: "Mr Racer",
      slug: "mr-racer",
      stars: "4.3",
      played: "189.4k",
    },
    {
      id: "271",
      name: "MagicParkour",
      url: "https://uptapapi.uptap.com/h5Game/?type=Game&platform=uptapin&appid=MagicParkour",
      icon: "https://cdn.iwantalipstick.com/gameicon2/jpg/MagicParkour.jpg",
      category: "Casual",
      description:
        "The road ahead is still very long with many obstacles, you need more resources to help you overcome them. Long press to overlay stairs with the bricks you collect on the road, do not approach the red region when you marching ahead. Try to collect more bricks so that you will achieve more rewards when you reach the final.",
      isPortrait: "True",
      time: "2021/5/21 18:48:00",
      title: "Magic Parkour",
      slug: "magic-parkour",
      stars: "4.4",
      played: "140.0k",
    },
    {
      id: "269",
      name: "FrozenMagic",
      url: "https://uptapapi.uptap.com/h5Game/?type=Game&platform=uptapin&appid=FrozenMagic",
      icon: "https://cdn.iwantalipstick.com/gameicon2/jpg/FrozenMagic.jpg",
      category: "Casual",
      description:
        "Anything can be frozen except my way! Keep cool, everything's in a flash! Help the princess go through her road. Tap to freeze the obstacles on your way, take care of the timing you freeze, make sure the frozen parts won't stop your steps. You can also collect gems on the road, freeze the rotating gems at the right time will help you collect more gems.",
      isPortrait: "True",
      time: "2021/5/21 18:48:00",
      title: "Frozen Magic",
      slug: "frozen-magic",
      stars: "4.2",
      played: "191.8k",
    },
    {
      id: "260",
      name: "TrafficRun",
      url: "https://uptapapi.uptap.com/h5Game/?type=Game&platform=uptapin&appid=TrafficRun",
      icon: "https://cdn.iwantalipstick.com/gameicon2/jpg/TrafficRun.jpg",
      category: "Casual",
      description:
        "If you are looking for a driving casual game, Traffic Run is the game you are looking for. Driving requires attention and askill. So with the help of your reflexes, try to reach the finish line without hitting other vehicles and collect gold coins. Be careful not to hit the other cars. This fun game will offer you a nice gaming experience.",
      isPortrait: "True",
      time: "2021/1/16 14:28:00",
      title: "Traffic Run",
      slug: "traffic-run",
      stars: "4.2",
      played: "176.8k",
    },
    {
      id: "258",
      name: "TrafficPassing",
      url: "https://uptapapi.uptap.com/h5Game/?type=Game&platform=uptapin&appid=TrafficPassing",
      icon: "https://cdn.iwantalipstick.com/gameicon2/jpg/TrafficPassing.jpg",
      category: "Casual",
      description:
        "Want to satisfy your challenge seeking, and make it really satisfying challenge. The ultimate Traffic Passing game is here! Think outside the box and you'll be expert of the game. Try this addicitve game and train your mind to solve each level, prove that ou are the smartest champion.",
      isPortrait: "True",
      time: "2021/1/14 14:28:00",
      title: "Traffic Passing",
      slug: "traffic-passing",
      stars: "4.5",
      played: "198.5k",
    },
    {
      id: "221",
      name: "SkyRunning3D",
      url: "https://uptapapi.uptap.com/h5Game/?type=Game&platform=uptapin&appid=SkyRunning3D",
      icon: "https://cdn.iwantalipstick.com/gameicon2/jpg/SkyRunning3D.jpg",
      category: "Casual",
      description:
        "Finish the race before your opponents do. Hold and drag to change the direction of where you are going to.",
      isPortrait: "True",
      time: "2020/11/26 16:51:00",
      title: "Sky Running 3D",
      slug: "sky-running-3d",
      stars: "4.4",
      played: "173.0k",
    },
    {
      id: "214",
      name: "MrBullet",
      url: "https://uptapapi.uptap.com/h5Game/?type=Game&platform=uptapin&appid=MrBullet",
      icon: "https://cdn.iwantalipstick.com/gameicon2/jpg/MrBullet.jpg",
      category: "Shooting",
      description:
        "The objective of the game is to kill off the bandits. Aim by holding and dragging your pointer to the desired trajectory in order to kill off the bandits. With each level completed you earn cash, with that cash you can purchase different types of skins and firearms.",
      isPortrait: "True",
      time: "2020/11/26 16:51:00",
      title: "Mr Bullet",
      slug: "mr-bullet",
      stars: "4.3",
      played: "152.6k",
    },
    {
      id: "208",
      name: "MergeAndDefense",
      url: "https://uptapapi.uptap.com/h5Game/?type=Game&platform=uptapin&appid=MergeAndDefense",
      icon: "https://cdn.iwantalipstick.com/gameicon2/jpg/MergeAndDefense.jpg",
      category: "Defense",
      description:
        "The aim of the game is to defend the egg from the upcoming enemies, and progress into the next levels. Merge two of the same characters by dragging them on top of each other to build up a stronger character. Fight off waves of  bugs and take down bosses to unlock new cards and abilities. Take a break and watch your cute characters do all the work for you while you are away. Come back to see your progress and claim your idle earnings.",
      isPortrait: "True",
      time: "2020/11/26 16:51:00",
      title: "Merge And Defense",
      slug: "merge-and-defense",
      stars: "4.2",
      played: "150.7k",
    },
    {
      id: "186",
      name: "FeverRacing",
      url: "https://uptapapi.uptap.com/h5Game/?type=Game&platform=uptapin&appid=FeverRacing",
      icon: "https://cdn.iwantalipstick.com/gameicon2/jpg/FeverRacing.jpg",
      category: "Action",
      description:
        "The objective of the game is to get the highest score possible. By tapping and holding, along with sliding around the screen to steer the vehicle. Maneuver your way around the other cars, follow the green arrow to collect different abilities to defend yourself and continue to rank up the score.",
      isPortrait: "True",
      time: "2020/11/26 16:51:00",
      title: "Fever Racing",
      slug: "fever-racing",
      stars: "4.3",
      played: "186.1k",
    },
    {
      id: "234",
      name: "ZombieSurvival",
      url: "https://uptapapi.uptap.com/h5Game/?type=Game&platform=uptapin&appid=ZombieSurvival",
      icon: "https://cdn.iwantalipstick.com/gameicon2/jpg/ZombieSurvival.jpg",
      category: "Action",
      description:
        "Kill off the other zombies by moving around the map, kill them to collect gold and level up your weapons, to progress in the game.",
      isPortrait: "True",
      time: "2020/6/24 18:11:00",
      title: "Zombie Survival",
      slug: "zombie-survival",
      stars: "4.3",
      played: "160.4k",
    },
    {
      id: "195",
      name: "HiTaxi",
      url: "https://uptapapi.uptap.com/h5Game/?type=Game&platform=uptapin&appid=HiTaxi",
      icon: "https://cdn.iwantalipstick.com/gameicon2/jpg/HiTaxi.jpg",
      category: "Casual",
      description:
        "Tap on to speed up and collect the customer, and drop him off at his final destination.",
      isPortrait: "True",
      time: "2020/6/19 18:11:00",
      title: "Hi Taxi",
      slug: "hi-taxi",
      stars: "4.3",
      played: "189.0k",
    },
    {
      id: "179",
      name: "CrazyMoto",
      url: "https://uptapapi.uptap.com/h5Game/?type=Game&platform=uptapin&appid=CrazyMoto",
      icon: "https://cdn.iwantalipstick.com/gameicon2/jpg/CrazyMoto.jpg",
      category: "Action",
      description:
        "Objective of the game is to finish the race first. Tap on the screen to speed up, collect weapons and abilities to knock the others off their bikes. Upgrade your motorbike, and props, to improve your racing abilities. Unlock maps by completing tasks and races. Login daily to receive amazing rewards. ",
      isPortrait: "True",
      time: "2020/6/19 18:11:00",
      title: "Crazy Moto",
      slug: "crazy-moto",
      stars: "4.2",
      played: "183.8k",
    },
    {
      id: "168",
      name: "BlockGun3D",
      url: "https://uptapapi.uptap.com/h5Game/?type=Game&platform=uptapin&appid=BlockGun3D",
      icon: "https://cdn.iwantalipstick.com/gameicon2/jpg/BlockGun3D.jpg",
      category: "Shooting",
      description:
        "Hold to shoot, place your target on the enemy and let go. Upgrade your weapons, helmet and armor to level up. Choose between different modes depending on your desired play.",
      isPortrait: "True",
      time: "2020/6/19 18:11:00",
      title: "Block Gun 3D",
      slug: "block-gun-3d",
      stars: "4.3",
      played: "156.6k",
    },
    {
      id: "162",
      name: "AceMan",
      url: "https://uptapapi.uptap.com/h5Game/?type=Game&platform=uptapin&appid=AceMan",
      icon: "https://cdn.iwantalipstick.com/gameicon2/jpg/AceMan.jpg",
      category: "Sports",
      description:
        "Tap on and hold until your preferred power has been reached, release and ace! You have scored into the hole.",
      isPortrait: "True",
      time: "2020/6/19 18:11:00",
      title: "Ace Man",
      slug: "ace-man",
      stars: "4.3",
      played: "123.3k",
    },
    {
      id: "178",
      name: "CrazyKnife",
      url: "https://uptapapi.uptap.com/h5Game/?type=Game&platform=uptapin&appid=CrazyKnife",
      icon: "https://cdn.iwantalipstick.com/gameicon2/jpg/CrazyKnife.jpg",
      category: "Action",
      description:
        "The objective of the game is to slice up all vegetables by tapping on the screen, and reach the end. Try to avoid slicing on the wooden or iron plates, as it makes you lose your streak and slows you down.",
      isPortrait: "True",
      time: "2020/6/18 18:11:00",
      title: "Crazy Knife",
      slug: "crazy-knife",
      stars: "4.3",
      played: "167.6k",
    },
    {
      id: "204",
      name: "LetMeIn",
      url: "https://uptapapi.uptap.com/h5Game/?type=Game&platform=uptapin&appid=LetMeIn",
      icon: "https://cdn.iwantalipstick.com/gameicon2/jpg/LetMeIn.jpg",
      category: "Strategy",
      description:
        "Collect as many people as possible, by tapping and holding to collect all. Upgrade your vehicle, to increase stability and load of people.",
      isPortrait: "True",
      time: "2020/6/17 18:11:00",
      title: "Let Me In",
      slug: "let-me-in",
      stars: "4.3",
      played: "141.3k",
    },
    {
      id: "216",
      name: "PetsMatch",
      url: "https://uptapapi.uptap.com/h5Game/?type=Game&platform=uptapin&appid=PetsMatch",
      icon: "https://cdn.iwantalipstick.com/gameicon2/jpg/PetsMatch.jpg",
      category: "Puzzle",
      description:
        "Find three or more identical squares in a row and eliminate them. Don't let the square top the top of the screen. There will be magical props to help you.",
      isPortrait: "True",
      time: "2020/6/15 18:11:00",
      title: "Pets Match",
      slug: "pets-match",
      stars: "4.3",
      played: "153.0k",
    },
    {
      id: "202",
      name: "Knife",
      url: "https://uptapapi.uptap.com/h5Game/?type=Game&platform=uptapin&appid=Knife",
      icon: "https://cdn.iwantalipstick.com/gameicon2/jpg/Knife.jpg",
      category: "Shooting",
      description:
        "Swipe around and aim at the enemies, before the map closes down on you. Upgrade your skills and weapons to increase the chances of you winning the game.",
      isPortrait: "True",
      time: "2020/6/15 18:11:00",
      title: "Knife",
      slug: "knife",
      stars: "4.3",
      played: "178.0k",
    },
    {
      id: "175",
      name: "ColorBall3D",
      url: "https://uptapapi.uptap.com/h5Game/?type=Game&platform=uptapin&appid=ColorBall3D",
      icon: "https://cdn.iwantalipstick.com/gameicon2/jpg/ColorBall3D.jpg",
      category: "Strategy",
      description:
        "Tap along to change the direction of the ball, once the ball on the map changes colour collect the specified ball colours.",
      isPortrait: "True",
      time: "2020/6/15 18:11:00",
      title: "Color Ball 3D",
      slug: "color-ball-3d",
      stars: "4.2",
      played: "129.9k",
    },
    {
      id: "190",
      name: "GoldenGlove",
      url: "https://uptapapi.uptap.com/h5Game/?type=Game&platform=uptapin&appid=GoldenGlove",
      icon: "https://cdn.iwantalipstick.com/gameicon2/jpg/GoldenGlove.jpg",
      category: "Sports",
      description:
        "Are you a catcher, choose your favourite sports team and demonstrate your skills by sliding your finger or mouse along the screen to catch the ball.",
      isPortrait: "True",
      time: "2020/6/14 18:11:00",
      title: "Golden Glove",
      slug: "golden-glove",
      stars: "4.5",
      played: "177.5k",
    },
    {
      id: "173",
      name: "BumbleShooter",
      url: "https://uptapapi.uptap.com/h5Game/?type=Game&platform=uptapin&appid=BumbleShooter",
      icon: "https://cdn.iwantalipstick.com/gameicon2/jpg/BumbleShooter.jpg",
      category: "Strategy",
      description:
        "The objective of the game is to get rid of all the bubbles and reach the desired score, to continue onto the next level. With the given bubble aim and tap to shoot at the colored set of bubbles to pop them all. To skip all the bubbles aim to clear a path and snap the bubble with the star, which will give you a huge amount of points and progress you onto the next level. ",
      isPortrait: "True",
      time: "2020/6/13 18:11:00",
      title: "Bumble Shooter",
      slug: "bumble-shooter",
      stars: "4.2",
      played: "185.3k",
    },
    {
      id: "187",
      name: "FireTheGun",
      url: "https://uptapapi.uptap.com/h5Game/?type=Game&platform=uptapin&appid=FireTheGun",
      icon: "https://cdn.iwantalipstick.com/gameicon2/jpg/FireTheGun.jpg",
      category: "Shooting",
      description:
        "When aiming at the range, tap on the yellow button to shoot and gain the most points by hitting the bullseye. Buy more weapons and merge the same two weapons to create a greater weapon.",
      isPortrait: "True",
      time: "2020/6/11 18:11:00",
      title: "Fire The Gun",
      slug: "fire-the-gun",
      stars: "4.4",
      played: "131.9k",
    },
    {
      id: "170",
      name: "BoardTheTrain",
      url: "https://uptapapi.uptap.com/h5Game/?type=Game&platform=uptapin&appid=BoardTheTrain",
      icon: "https://cdn.iwantalipstick.com/gameicon2/jpg/BoardTheTrain.jpg",
      category: "Casual",
      description:
        "The objective of the game is to collect all the passengers, and go through the map and its obstacles, to reach the final destination. You play by tapping and holding on the screen. ",
      isPortrait: "True",
      time: "2020/6/10 18:11:00",
      title: "Board The Train",
      slug: "board-the-train",
      stars: "4.4",
      played: "192.7k",
    },
    {
      id: "233100",
      name: "DashCat",
      url: "https://uptapapi.uptap.com/h5Game/?type=Game&platform=uptapin&appid=BoardTheTrain",
      icon: "https://cdn.iwantalipstick.com/gameicon2/jpg/DashCat.jpg",
      category: "Casual",
      description:
        "Dash to catch the rolling cat. You need to draw a line to make the cat roll further.Make sure the cat doesn't fall to the ground.The ink will be used up.",
      isPortrait: "True",
      time: "2022/8/20 18:11:00",
      title: "Dash Cat",
      slug: "dash-cat",
      stars: "4.3",
      played: "449.7k",
    },
    {
      id: "233101",
      name: "SpinTheMaze",
      url: "https://uptapapi.uptap.com/h5Game/?type=Game&platform=uptapin&appid=SpinTheMaze",
      icon: "https://cdn.iwantalipstick.com/gameicon2/jpg/SpinTheMaze.jpg",
      category: "Puzzle",
      description:
        "Spin the maze and make the ball out. There are stars in the maze, you need to collect as more stars as possible.",
      isPortrait: "True",
      time: "2022/8/20 18:11:00",
      title: "Spin The Maze",
      slug: "spin-the-maze",
      stars: "4.3",
      played: "135.3k",
    },
    {
      id: "233102",
      name: "SuperSoccer",
      url: "https://uptapapi.uptap.com/h5Game/?type=Game&platform=uptapin&appid=SuperSoccer",
      icon: "https://cdn.iwantalipstick.com/gameicon2/jpg/SuperSoccer.jpg",
      category: "Action",
      description:
        "Your goal is to shoot the ball into the goal. Pass the ball to your teammate,try to make the ball to the goal.You need to control the passing angle to avoid being intercepted by the opponent.",
      isPortrait: "True",
      time: "2022/8/20 18:11:00",
      title: "Super Soccer",
      slug: "super-soccer",
      stars: "4.3",
      played: "322.1k",
    },
  ],
  categories: [
    "Action",
    "Casual",
    "Defense",
    "Puzzle",
    "Racing",
    "Shooting",
    "Simulation",
    "Sports",
    "Strategy",
  ],
};
